export const POSTS = {
    INITIALISE: "INITIALISE_POSTS",
    FEED: "ADD_TO_FEED",
    SET_SORT: "SORT_BY"
}

export const USERS = {
    INITIALISE: "INITIALISE_USERS",
    FOLLOW: "FOLLOW"
}

export const AUTH = {
    LOGIN: "LOGIN",
    SET_BOOKMARKS: "SET_BOOKMARKS",
    LOGOUT: "LOGOUT"
}